name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_VERBOSE_LOGGING: true

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add Nx Cloud distributed task execution
      - name: Start Nx Cloud CI Run
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after=build

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Cache node_modules
      - name: Restore cached dependencies
        id: cache-dependencies-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
          key: npm-dependencies-${{ hashFiles('package-lock.json') }}

      - run: npm ci

      - name: Save dependencies cache
        id: cache-dependencies-save
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
          key: ${{ steps.cache-dependencies-restore.outputs.cache-primary-key }}

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build --parallel=3
